export const colorTokens = {
  transparent: "transparent",
  black: "#000",
  neutral: {
    0: "#fff",
    10: "#fafafa",
    50: "#f4f4f4",
    100: "#efefef",
    200: "#dfdfdf",
    300: "#ccc",
    400: "#bfbfbf",
    450: "#afafaf",
    500: "#a0a0a0",
    550: "#909090",
    600: "#707070",
    700: "#5a5a5a",
    750: "#555D65",
    800: "#3f3f3f",
    850: "#3a3a3a",
    900: "#242424",
    925: "#20252A",
    950: "#20242b",
    975: "#1a1a1a",
    1000: "#141414",
  },
  accent: {
    lightSelection: "#44e588",
    darkSelection: "#e28f38",
    lightStack: "#98e6cf",
    darkStack: "#2D6C90",
  },
  alpha: {
    lightScrollbar: "rgba(26,26,26,0.6)",
    darkScrollbar: "rgba(90,90,90,0.6)",
    lightStack: "rgba(255,255,255,0.24)",
    darkStack: "rgba(255, 255, 255, 0.16)",
  },
} as const;

const light = {
  page: {
    bg: colorTokens.neutral[0],
    selectionBg: colorTokens.accent.lightSelection,
    selectionText: colorTokens.neutral[850],
  },
  cursor: {
    basic: colorTokens.neutral[975],
    hover: colorTokens.neutral[975],
  },
  scrollbar: { thumb: colorTokens.alpha.lightScrollbar },
  buttons: {
    basic: colorTokens.neutral[700],
    hoverBg: colorTokens.neutral[800],
    hoverContents: colorTokens.neutral[0],
  },
  transCover: {
    bg: colorTokens.neutral[850],
    title: colorTokens.neutral[0],
  },
  initCover: {
    icon: colorTokens.neutral[0],
    text: colorTokens.neutral[200],
  },
  timer: {
    bar: colorTokens.neutral[400],
    text: colorTokens.neutral[400],
  },
  gnbSitemapBtn: {
    basic: colorTokens.neutral[400],
    hover: colorTokens.neutral[700],
    selected: colorTokens.neutral[850],
  },
  gnbUtilBtn: {
    bg: colorTokens.neutral[100],
    svg: colorTokens.neutral[600],
    svgHover: colorTokens.neutral[700],
    svgActive: colorTokens.neutral[975],
    tooltipBox: colorTokens.neutral[500],
    tooltipText: colorTokens.neutral[0],
  },
  gnbThemeMenu: {
    container: colorTokens.neutral[100],
    menu: colorTokens.neutral[450],
    hover: colorTokens.neutral[600],
    selected: colorTokens.neutral[850],
  },
  sectionHeader: {
    title: colorTokens.neutral[850],
    desc: colorTokens.neutral[700],
  },
  visualSection: {
    border: colorTokens.neutral[975],
    fill: colorTokens.neutral[975],
  },
  introSection: {
    bgFrom: "rgb(255, 255, 255)",
    bgTo: "rgba(255, 255, 255, 0)",
    title: colorTokens.neutral[850],
    strong: colorTokens.neutral[975],
    desc: colorTokens.neutral[700],
  },
  footer: {
    bg: colorTokens.neutral[100],
    titleBorder: colorTokens.neutral[550],
    titleFill: colorTokens.neutral[700],
    summary: colorTokens.neutral[600],
    copyright: colorTokens.neutral[600],
    linkCategory: colorTokens.neutral[600],
    link: colorTokens.neutral[550],
    linkIcon: colorTokens.neutral[550],
    linkHover: colorTokens.neutral[850],
    tooltipBox: colorTokens.neutral[700],
    tooltipText: colorTokens.neutral[0],
  },
  career: {
    border: colorTokens.neutral[500],
    borderHover: colorTokens.neutral[700],
    bgHover: colorTokens.transparent,
    period: colorTokens.neutral[300],
    periodHover: colorTokens.neutral[850],
    role: colorTokens.neutral[975],
    roleHover: colorTokens.neutral[975],
    company: colorTokens.neutral[700],
    companyHover: colorTokens.neutral[850],
    detailTitle: colorTokens.neutral[700],
    detailContents: colorTokens.neutral[550],
    icon: colorTokens.neutral[600],
    iconHover: colorTokens.neutral[850],
    expandBg: colorTokens.neutral[50],
  },
  exp: {
    title: colorTokens.neutral[850],
    desc: colorTokens.neutral[600],
  },
  stacks: {
    legendTitle: colorTokens.neutral[700],
    legendLabel: colorTokens.neutral[500],
    border: colorTokens.neutral[200],
    category: colorTokens.neutral[600],
    stackName: colorTokens.neutral[700],
    levelFill: colorTokens.neutral[850],
    levelEmpty: colorTokens.neutral[200],
    levelFull: colorTokens.accent.lightStack,
  },
  projectList: {
    border: colorTokens.neutral[300],
    bgHover: colorTokens.neutral[100],
    title: colorTokens.neutral[700],
    period: colorTokens.neutral[400],
    desc: colorTokens.neutral[600],
    slideTitle: colorTokens.neutral[700],
  },
  projectDetails: {
    bg: "rgb(255, 255, 255)",
    visualBg: `linear-gradient(
      0deg,
      rgba(255, 255, 255, 1) 5%,
      rgba(255, 255, 255, 0.8) 100%
    )`,
    visualTitle: colorTokens.neutral[850],
    visualSubtitle: colorTokens.neutral[550],
    infoTitle: colorTokens.neutral[600],
    infoDesc: colorTokens.neutral[700],
    expTitle: colorTokens.neutral[700],
    expDesc: colorTokens.neutral[600],
    stackBg: colorTokens.alpha.lightStack,
    stackBorder: colorTokens.neutral[500],
    stackText: colorTokens.neutral[700],
    captionTitle: colorTokens.neutral[975],
    captionDesc: colorTokens.neutral[700],
  },
} as const;

const dark: ThemeTokens = {
  page: {
    bg: colorTokens.neutral[1000],
    selectionBg: colorTokens.accent.darkSelection,
    selectionText: colorTokens.neutral[0],
  },
  cursor: {
    basic: colorTokens.neutral[0],
    hover: colorTokens.neutral[0],
  },
  scrollbar: { thumb: colorTokens.alpha.darkScrollbar },
  buttons: {
    basic: colorTokens.neutral[0],
    hoverBg: colorTokens.neutral[0],
    hoverContents: colorTokens.neutral[850],
  },
  transCover: {
    bg: colorTokens.neutral[950],
    title: colorTokens.neutral[0],
  },
  initCover: {
    icon: colorTokens.neutral[200],
    text: colorTokens.neutral[600],
  },
  timer: {
    bar: colorTokens.neutral[700],
    text: colorTokens.neutral[700],
  },
  gnbSitemapBtn: {
    basic: colorTokens.neutral[700],
    hover: colorTokens.neutral[0],
    selected: colorTokens.neutral[300],
  },
  gnbUtilBtn: {
    bg: colorTokens.neutral[850],
    svg: colorTokens.neutral[600],
    svgHover: colorTokens.neutral[300],
    svgActive: colorTokens.neutral[0],
    tooltipBox: colorTokens.neutral[500],
    tooltipText: colorTokens.neutral[0],
  },
  gnbThemeMenu: {
    container: colorTokens.neutral[850],
    menu: colorTokens.neutral[600],
    hover: colorTokens.neutral[400],
    selected: colorTokens.neutral[200],
  },
  sectionHeader: {
    title: colorTokens.neutral[200],
    desc: colorTokens.neutral[600],
  },
  visualSection: {
    border: colorTokens.neutral[10],
    fill: colorTokens.neutral[10],
  },
  introSection: {
    bgFrom: "rgb(26, 26, 26)",
    bgTo: "rgba(26, 26, 26, 0)",
    title: colorTokens.neutral[200],
    strong: colorTokens.neutral[200],
    desc: colorTokens.neutral[500],
  },
  footer: {
    bg: colorTokens.neutral[925],
    titleBorder: colorTokens.neutral[500],
    titleFill: colorTokens.neutral[200],
    summary: colorTokens.neutral[550],
    copyright: colorTokens.neutral[550],
    linkCategory: colorTokens.neutral[600],
    link: colorTokens.neutral[400],
    linkIcon: colorTokens.neutral[600],
    linkHover: colorTokens.neutral[0],
    tooltipBox: colorTokens.neutral[750],
    tooltipText: colorTokens.neutral[0],
  },
  career: {
    border: colorTokens.neutral[850],
    borderHover: colorTokens.neutral[700],
    bgHover: colorTokens.transparent,
    period: colorTokens.neutral[700],
    periodHover: colorTokens.neutral[400],
    role: colorTokens.neutral[200],
    roleHover: colorTokens.neutral[0],
    company: colorTokens.neutral[550],
    companyHover: colorTokens.neutral[200],
    detailTitle: colorTokens.neutral[200],
    detailContents: colorTokens.neutral[500],
    icon: colorTokens.neutral[600],
    iconHover: colorTokens.neutral[0],
    expandBg: colorTokens.neutral[975],
  },
  exp: {
    title: colorTokens.neutral[200],
    desc: colorTokens.neutral[550],
  },
  stacks: {
    legendTitle: colorTokens.neutral[200],
    legendLabel: colorTokens.neutral[600],
    border: colorTokens.neutral[700],
    category: colorTokens.neutral[700],
    stackName: colorTokens.neutral[200],
    levelFill: colorTokens.neutral[0],
    levelEmpty: colorTokens.neutral[850],
    levelFull: colorTokens.accent.darkStack,
  },
  projectList: {
    border: colorTokens.neutral[850],
    bgHover: colorTokens.neutral[900],
    title: colorTokens.neutral[700],
    period: colorTokens.neutral[700],
    desc: colorTokens.neutral[600],
    slideTitle: colorTokens.neutral[0],
  },
  projectDetails: {
    bg: "rgb(26,26,26)",
    visualBg: `linear-gradient(
      0deg,
      rgba(26, 26, 26, 1) 5%,
      rgba(26, 26, 26, 0.6) 100%
    )`,
    visualTitle: colorTokens.neutral[0],
    visualSubtitle: colorTokens.neutral[550],
    infoTitle: colorTokens.neutral[550],
    infoDesc: colorTokens.neutral[400],
    expTitle: colorTokens.neutral[200],
    expDesc: colorTokens.neutral[550],
    stackBg: colorTokens.alpha.darkStack,
    stackBorder: colorTokens.neutral[600],
    stackText: colorTokens.neutral[300],
    captionTitle: colorTokens.neutral[0],
    captionDesc: colorTokens.neutral[500],
  },
};

export const themeTokens = { light, dark } as const;

export type ThemeMode = keyof typeof themeTokens;
export type ThemeTokens = {
  [Group in keyof typeof light]: {
    [Token in keyof (typeof light)[Group]]: string;
  };
};
