export const colors = {
  transparent: "transparent",
  black: "#000",
  neutral: {
    0: "#fff",
    10: "#fafafa",
    50: "#f4f4f4",
    100: "#efefef",
    200: "#dfdfdf",
    300: "#ccc",
    400: "#bfbfbf",
    450: "#afafaf",
    500: "#a0a0a0",
    550: "#909090",
    600: "#707070",
    700: "#5a5a5a",
    750: "#555D65",
    800: "#3f3f3f",
    850: "#3a3a3a",
    900: "#242424",
    925: "#20252A",
    950: "#20242b",
    975: "#1a1a1a",
    1000: "#141414",
  },
  accent: {
    lightSelection: "#44e588",
    darkSelection: "#e28f38",
    lightStack: "#98e6cf",
    darkStack: "#2D6C90",
  },
  alpha: {
    lightScrollbar: "rgba(26,26,26,0.6)",
    darkScrollbar: "rgba(90,90,90,0.6)",
    lightStack: "rgba(255,255,255,0.24)",
    darkStack: "rgba(255, 255, 255, 0.16)",
  },
} as const;

const light = {
  page: {
    bg: colors.neutral[0],
    selectionBg: colors.accent.lightSelection,
    selectionText: colors.neutral[850],
  },
  cursor: {
    basic: colors.neutral[975],
    hover: colors.neutral[975],
  },
  scrollbar: { thumb: colors.alpha.lightScrollbar },
  buttons: {
    basic: colors.neutral[700],
    hoverBg: colors.neutral[800],
    hoverContents: colors.neutral[0],
  },
  transCover: {
    bg: colors.neutral[850],
    title: colors.neutral[0],
  },
  initCover: {
    icon: colors.neutral[0],
    text: colors.neutral[200],
  },
  timer: {
    bar: colors.neutral[400],
    text: colors.neutral[400],
  },
  gnbSitemapBtn: {
    basic: colors.neutral[400],
    hover: colors.neutral[700],
    selected: colors.neutral[850],
  },
  gnbUtilBtn: {
    bg: colors.neutral[100],
    svg: colors.neutral[600],
    svgHover: colors.neutral[700],
    svgActive: colors.neutral[975],
    tooltipBox: colors.neutral[500],
    tooltipText: colors.neutral[0],
  },
  gnbThemeMenu: {
    container: colors.neutral[100],
    menu: colors.neutral[450],
    hover: colors.neutral[600],
    selected: colors.neutral[850],
  },
  sectionHeader: {
    title: colors.neutral[850],
    desc: colors.neutral[700],
  },
  visualSection: {
    border: colors.neutral[975],
    fill: colors.neutral[975],
  },
  introSection: {
    bgFrom: "rgb(255, 255, 255)",
    bgTo: "rgba(255, 255, 255, 0)",
    title: colors.neutral[850],
    strong: colors.neutral[975],
    desc: colors.neutral[700],
  },
  footer: {
    bg: colors.neutral[100],
    titleBorder: colors.neutral[550],
    titleFill: colors.neutral[700],
    summary: colors.neutral[600],
    copyright: colors.neutral[600],
    linkCategory: colors.neutral[600],
    link: colors.neutral[550],
    linkIcon: colors.neutral[550],
    linkHover: colors.neutral[850],
    tooltipBox: colors.neutral[700],
    tooltipText: colors.neutral[0],
  },
  career: {
    border: colors.neutral[500],
    borderHover: colors.neutral[700],
    bgHover: colors.transparent,
    period: colors.neutral[300],
    periodHover: colors.neutral[850],
    role: colors.neutral[975],
    roleHover: colors.neutral[975],
    company: colors.neutral[700],
    companyHover: colors.neutral[850],
    detailTitle: colors.neutral[700],
    detailContents: colors.neutral[550],
    icon: colors.neutral[600],
    iconHover: colors.neutral[850],
    expandBg: colors.neutral[50],
  },
  exp: {
    title: colors.neutral[850],
    desc: colors.neutral[600],
  },
  stacks: {
    legendTitle: colors.neutral[700],
    legendLabel: colors.neutral[500],
    border: colors.neutral[200],
    category: colors.neutral[600],
    stackName: colors.neutral[700],
    levelFill: colors.neutral[850],
    levelEmpty: colors.neutral[200],
    levelFull: colors.accent.lightStack,
  },
  projectList: {
    border: colors.neutral[300],
    bgHover: colors.neutral[100],
    title: colors.neutral[700],
    period: colors.neutral[400],
    desc: colors.neutral[600],
    slideTitle: colors.neutral[700],
  },
  projectDetails: {
    bg: "rgb(255, 255, 255)",
    visualBg: `linear-gradient(
      0deg,
      rgba(255, 255, 255, 1) 5%,
      rgba(255, 255, 255, 0.8) 100%
    )`,
    visualTitle: colors.neutral[850],
    visualSubtitle: colors.neutral[550],
    infoTitle: colors.neutral[600],
    infoDesc: colors.neutral[700],
    expTitle: colors.neutral[700],
    expDesc: colors.neutral[600],
    stackBg: colors.alpha.lightStack,
    stackBorder: colors.neutral[500],
    stackText: colors.neutral[700],
    captionTitle: colors.neutral[975],
    captionDesc: colors.neutral[700],
  },
} as const;

const dark: Theme = {
  page: {
    bg: colors.neutral[1000],
    selectionBg: colors.accent.darkSelection,
    selectionText: colors.neutral[0],
  },
  cursor: {
    basic: colors.neutral[0],
    hover: colors.neutral[0],
  },
  scrollbar: { thumb: colors.alpha.darkScrollbar },
  buttons: {
    basic: colors.neutral[0],
    hoverBg: colors.neutral[0],
    hoverContents: colors.neutral[850],
  },
  transCover: {
    bg: colors.neutral[950],
    title: colors.neutral[0],
  },
  initCover: {
    icon: colors.neutral[200],
    text: colors.neutral[600],
  },
  timer: {
    bar: colors.neutral[700],
    text: colors.neutral[700],
  },
  gnbSitemapBtn: {
    basic: colors.neutral[700],
    hover: colors.neutral[0],
    selected: colors.neutral[300],
  },
  gnbUtilBtn: {
    bg: colors.neutral[850],
    svg: colors.neutral[600],
    svgHover: colors.neutral[300],
    svgActive: colors.neutral[0],
    tooltipBox: colors.neutral[500],
    tooltipText: colors.neutral[0],
  },
  gnbThemeMenu: {
    container: colors.neutral[850],
    menu: colors.neutral[600],
    hover: colors.neutral[400],
    selected: colors.neutral[200],
  },
  sectionHeader: {
    title: colors.neutral[200],
    desc: colors.neutral[600],
  },
  visualSection: {
    border: colors.neutral[10],
    fill: colors.neutral[10],
  },
  introSection: {
    bgFrom: "rgb(26, 26, 26)",
    bgTo: "rgba(26, 26, 26, 0)",
    title: colors.neutral[200],
    strong: colors.neutral[200],
    desc: colors.neutral[500],
  },
  footer: {
    bg: colors.neutral[925],
    titleBorder: colors.neutral[500],
    titleFill: colors.neutral[200],
    summary: colors.neutral[550],
    copyright: colors.neutral[550],
    linkCategory: colors.neutral[600],
    link: colors.neutral[400],
    linkIcon: colors.neutral[600],
    linkHover: colors.neutral[0],
    tooltipBox: colors.neutral[750],
    tooltipText: colors.neutral[0],
  },
  career: {
    border: colors.neutral[850],
    borderHover: colors.neutral[700],
    bgHover: colors.transparent,
    period: colors.neutral[700],
    periodHover: colors.neutral[400],
    role: colors.neutral[200],
    roleHover: colors.neutral[0],
    company: colors.neutral[550],
    companyHover: colors.neutral[200],
    detailTitle: colors.neutral[200],
    detailContents: colors.neutral[500],
    icon: colors.neutral[600],
    iconHover: colors.neutral[0],
    expandBg: colors.neutral[975],
  },
  exp: {
    title: colors.neutral[200],
    desc: colors.neutral[550],
  },
  stacks: {
    legendTitle: colors.neutral[200],
    legendLabel: colors.neutral[600],
    border: colors.neutral[700],
    category: colors.neutral[700],
    stackName: colors.neutral[200],
    levelFill: colors.neutral[0],
    levelEmpty: colors.neutral[850],
    levelFull: colors.accent.darkStack,
  },
  projectList: {
    border: colors.neutral[850],
    bgHover: colors.neutral[900],
    title: colors.neutral[700],
    period: colors.neutral[700],
    desc: colors.neutral[600],
    slideTitle: colors.neutral[0],
  },
  projectDetails: {
    bg: "rgb(26,26,26)",
    visualBg: `linear-gradient(
      0deg,
      rgba(26, 26, 26, 1) 5%,
      rgba(26, 26, 26, 0.6) 100%
    )`,
    visualTitle: colors.neutral[0],
    visualSubtitle: colors.neutral[550],
    infoTitle: colors.neutral[550],
    infoDesc: colors.neutral[400],
    expTitle: colors.neutral[200],
    expDesc: colors.neutral[550],
    stackBg: colors.alpha.darkStack,
    stackBorder: colors.neutral[600],
    stackText: colors.neutral[300],
    captionTitle: colors.neutral[0],
    captionDesc: colors.neutral[500],
  },
};

export const themes = { light, dark } as const;

export type ThemeMode = keyof typeof themes;
export type Theme = {
  [Group in keyof typeof light]: {
    [Token in keyof (typeof light)[Group]]: string;
  };
};
