import { CareerModeTypes } from "@/types/colors/profile";

export const career: CareerModeTypes = {
  light: {
    border: "#a0a0a0",
    borderHover: "#5a5a5a",
    bgHover: "transparent",
    period: "#ccc",
    periodHover: "#3a3a3a",
    role: "#1a1a1a",
    roleHover: "#1a1a1a",
    company: "#5a5a5a",
    companyHover: "#3a3a3a",
    detailTitle: "#5a5a5a",
    detailContents: "#909090",
    icon: "#707070",
    iconHover: "#3a3a3a",
    expandBg: "#f4f4f4",
  },
  dark: {
    border: "#3a3a3a",
    borderHover: "#5a5a5a",
    bgHover: "transparent",
    period: "#5a5a5a",
    periodHover: "#bfbfbf",
    role: "#dfdfdf",
    roleHover: "#fff",
    company: "#909090",
    companyHover: "#dfdfdf",
    detailTitle: "#dfdfdf",
    detailContents: "#a0a0a0",
    icon: "#707070",
    iconHover: "#fff",
    expandBg: "#1a1a1a",
  },
};
